### ISSUE TITLE
Is there a way to have a different relationship than HAS_STATE?

### ISSUE THREAD

**Issue by aferg** [h-omer/neo4j-versioner-core#10]
Trying to integrate your plugin into an existing platform solution but it's already making use of HAS_STATE relationships and this results in some failures in platform queries when versioner core states are in there with HAS_STATE relationships.

Is it possible to configure the relationship, say I wanted to use maybe HAS_VERSION instead?

Not really another alternative option for me, I can't change the platform code.

**Comment by mfalcier** [comment]
Hi @aferg , I'm sorry, but unfortunately it's not possible at the moment.
