### ISSUE TITLE
Unable to build master or 2.0.0 branches without failing unit tests

### ISSUE THREAD

**Issue by aferg** [h-omer/neo4j-versioner-core#11]
I have cloned master and when building locally get the following failing unit tests as included in screen shot.

<img width="787" alt="Screen Shot 2020-04-01 at 11 54 21 AM" src="https://user-images.githubusercontent.com/2230435/78158907-d976e280-740f-11ea-909b-e653cdb77a86.png">

Edit: looks like the same tests fail in 2.0.0 branch as well

**Comment by mfalcier** [comment]
Hi @aferg I'm sorry, but I can't reproduce your issue on both my laptop and my desktop pc. Have you tried bulding it directly from gradle on command line?

**Comment by tschn** [comment]
#13 fixes this issue, related to timezone issues in test (explains why it works for certain timezones but not others), long date is now converted to string and used for both data entry and assertion
