### ISSUE TITLE
Support for Neo4j v4.0+

### ISSUE THREAD

**Issue by BHunter2889** [h-omer/neo4j-versioner-core#12]
**Describe the bug**
We keep getting at `ProcedureCallFailed` error when trying to run the `graph.versioner.init` call provided in the documentation for `neo4j-versioner-core`. (see screenshot)
Running `dbms,procedures()` lists everything from `graph.versioner.*` but on the rightmost column under `worksOnSystem`, the value is `false` for each one. 
After researching though your and Neo4j documentation with no luck, I decided to come back to your issues and found a similar one in #6 which seems to address prior version upgrade breaking changes. 
I believe this has happened once again in the 4.0+ upgrade based on what I'm seeing but I'll add the caveat that I'm relatively new to Neo4j.

We'll need to know that any solution we implement on this client project will be future-safe so I'll add a question to this issue: Should be able to expect that kind of support or if you happen to know of something that would provide that that may not be as optimal of a solution otherwise? 

**To Reproduce**
1. Install neo4j v4.0.2 (community)
2. Run neo4j and open the browser console
3. Run the `CALL graph.versioner.init...` command provided in your documentation.
4. You should see the error described and in the screenshot.

**Expected behavior**
Call to work as described and expected with latest version of Neo4j.

**Screenshots**
![versioner-procedureCallFailed](https://user-images.githubusercontent.com/23201149/78277537-51114400-74da-11ea-84e2-3b8464118c65.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.0.4 running in WSL
 - Browser: Opera (for running neo4j browser console
 - Version: `neo4j-versioner-core 2.0.0` & Neo4j 4.0.2 (community)

**Comment by mfalcier** [comment]
Hi @BHunter2889 , we haven't started our support for the new Neo4j version 4.x, so I guess that's why you're having this issue. 
We'll try to do our best in order to have an updated version as soon as possible.

**Comment by mnlsbn** [comment]
Hi @mfalcier, do you have any update on this ? i'm facing the same issue as @BHunter2889.
Correct me if i'm wrong, but I did not find a way to downgrade my Neo4j version.
I'm currently using Desktop version 4.0.3 and neo4j-versioner-core 2.0.0
Thanks for your support

**Comment by bandaja** [comment]
I have the same issue with Neo4j 4.1.1, so I decided to uninstall Neo4j 4.1.1 and Install Neo4j 3.5.21, but still I have the same error. What version of PostgreSQL JDBC do I need to use?

**Comment by mfalcier** [comment]
@mnlsbn @bandaja @BHunter2889 We are currently working on 4.2 support.

**Comment by IanMack-uk** [comment]
> I have the same issue with Neo4j 4.1.1, so I decided to uninstall Neo4j 4.1.1 and Install Neo4j 3.5.21, but still I have the same error. What version of PostgreSQL JDBC do I need to use?

Hey @bandaja - yes, I'm considering installing Neo4j 3.5 to get the versioner-core working - but wanted to know if you had got it working yet? Do you need to add anything to config settings? Cheers, Ian

**Comment by mfalcier** [comment]
New release with version 4.2 support.
https://github.com/h-omer/neo4j-versioner-core/releases/tag/4.2.4
