### ISSUE TITLE
Question about the R in the Entity-State-R (ESR) Data Model

### ISSUE THREAD

**Issue by cs224** [h-omer/neo4j-versioner-core#14]
Hello,

I have a question about the reasoning behind introducing the R in the Entity-State-R (ESR) Data Model. Could you please explain why this extra node is necessary? If there is a standard theory behind this model then please simply point me to a document explaining that theory.

Thanks a lot!
Christian

**Comment by mfalcier** [comment]
Hello Christian, R node was introduced for performance reasons, due to the Entity node being potentially connected with a lot of State nodes. Splitting this up helped with that, since entities could have many relationships with other entities.
