### ISSUE TITLE
Neo.ClientError.Procedure.ProcedureCallFailed

### ISSUE THREAD

**Issue by IanMack-uk** [h-omer/neo4j-versioner-core#16]
Hi guys,

when I use use your example line CALL graph.versioner.init('Person', {ssn: localdatetime('1988-10-27T02:46:40'), name: 'Marco'}, {address: 'Via Roma 11'}) YIELD node RETURN node

Neo4j returns this error

Neo.ClientError.Procedure.ProcedureCallFailed

Failed to invoke procedure `graph.versioner.init`: Caused by: java.lang.NoSuchMethodError: 'org.neo4j.graphdb.Node org.neo4j.graphdb.GraphDatabaseService.createNode(org.neo4j.graphdb.Label[])'

I'm on Neo4j v1.4.1

Any ideas as to a fix?
Many thanks,
Ian

**Comment by mfalcier** [comment]
New release with version 4.2 support.
https://github.com/h-omer/neo4j-versioner-core/releases/tag/4.2.4

**Comment by IanMack-uk** [comment]
Thanks Marco. Appreciate it.

Ian Mack

e: ***@***.***
p: +44 7921 264 265
