### ISSUE TITLE
Neo.ClientError.Procedure.ProcedureNotFound

### ISSUE THREAD

**Issue by Rajeswara-Rao** [h-omer/neo4j-versioner-core#17]
I have successfully kept neo4j-versioner jar file in my plugins folder and try to run the following query.
```
CALL graph.versioner.init('Element', {name:"Neo4j"}, {status:'Initialized'}, 'Ready')
YIELD node
RETURN node
```
When I am running it I got this error

There is no procedure with the name `graph.versioner.init` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

I am using neo4j instance with version 3.5.24 in AWS platform.

Please help me to resolve this issue.
Thanks in advance!

**Comment by mfalcier** [comment]
Hi @Rajeswara-Rao , have you tried reproducing this issue on a local Neo4j db?

**Comment by Rajeswara-Rao** [comment]
Hi @mfalcier , I have done the same thing in local Neo4j Desktop. It is working fine there , but facing issue in AWS sever.

**Comment by mfalcier** [comment]
Hi @Rajeswara-Rao , I guess there's an issue when you "deploy" our versioner into your remote Neo4j on AWS.

That error shows that the init procedure is not registered, so somehow that instance can't "see" that you've deployed our library.

**Comment by Rajeswara-Rao** [comment]
Hello @mfalcier  , While creating Neo4j instance I had mapped to wrong plugins folder which created this issue. Now it is working fine.
Thanks for your support!!
