### ISSUE TITLE
Looking for recommendation

### ISSUE THREAD

**Issue by sambathl** [h-omer/neo4j-versioner-core#5]
I am creating version state for tree structure - update of relation, removal of relation, removal of node and adding of node. Is there any recommendation got this use case :) ?

**Comment by mfalcier** [comment]
Hi, we're currently working on adding full relationship versioning.

If you want you can take a look at our 2.0.0 branch.

**Comment by mfalcier** [comment]
Take a look at our last 2.0.0 relase, we're managing relationships now.
