### ISSUE TITLE
Delete date for relationships is not used as endDate in State

### ISSUE THREAD

**Issue by EliuX** [h-omer/neo4j-versioner-core#7]
**Describe the bug**
When I use `graph.versioner.relationship.delete` and specify the `date` parameter the `endDate` of the updated State, who had this relationship for the last time, will have the currentDate instead of that date I specified.

**To Reproduce**
1. Create a relationship specifying a `date`, e.g. Nov 2nd of 2019. You will notice that the `startDate` will point to that date
2. Delete that relationship and specify another `date`, e.g. Nov 3 of 2019. You will see that the endDate instead of being Nov 3rd of 2019 it will be the current date.

**Expected behavior**
I would expect that if I delete a relationship on a particular date that would be the `endDate` of the last State who had such a relationship.

**Desktop (please complete the following information):**
 - OS: Mac Os Mohave
 - Browser Chrome
 - Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by mfalcier** [comment]
Hi, can you please provide us all the Query/Procedures call you made in order to replicate this issue? It will help us a lot. Thanks!

**Comment by mfalcier** [comment]
Closing this issue since there are no answers.

**Comment by EliuX** [comment]
Sorry, I have no access to a Neo4J code for a long time. Also I dont have right now a set of queries to fill the database.  Basically the error happens when using the procedure for deletions. 
In the description I explained how to reproduce the error and what is expected, which could be tested with pretty much any set of data compatible with this library.
Thanks anyway for the library :)

**Comment by mfalcier** [comment]
It's solved in the current release then ;)
