### ISSUE TITLE
delete a relationship removes all LINKS of the entitySource

### ISSUE THREAD

**Issue by EliuX** [h-omer/neo4j-versioner-core#8]
**Describe the bug**
If you have a node `A` with multiple relationships of type `X` with B, C, and D having him as the source entity, if you execute

```
CALL graph.versioner.relationship.delete(A, B, 'X')
```
the new current `State` of `A` will have not have any relationship of type `X` coming out of it. 

**To Reproduce**
1. Create multiple entities
```
CALL graph.versioner.init('Entity', {name: 'Entity1'}, {address: 'Via Roma 11'}) YIELD node RETURN node
CALL graph.versioner.init('Entity', {name: 'Entity2'}, {address: 'Via Roma 12'}) YIELD node RETURN node
CALL graph.versioner.init('Entity', {name: 'Entity3'}, {address: 'Via Roma 13'}) YIELD node RETURN node
```
2. Then create a relationship between Entity1 and the rest of the entities
```
MATCH (e1:Entity {name:'Entity1'}), (e2:Entity {name:'Entity2'}),(e3:Entity {name:'Entity3'}) WITH e1, e2, e3 
CALL graph.versioner.relationship.create(e1, e2, 'REL') YIELD relationship AS rel12
CALL graph.versioner.relationship.create(e1, e3, 'REL') YIELD relationship AS rel13
RETURN rel12, rel13
```
After running this the graph shall look like this

![image](https://user-images.githubusercontent.com/6514740/69754628-60474600-1124-11ea-8ef1-f7c0f27e9617.png)

3. Lets now remove the relationship between the entity1 and entity2
```
MATCH (e1:Entity {name:'Entity1'}), (e2:Entity {name:'Entity2'})
CALL graph.versioner.relationship.delete(e1, e2, 'REL') YIELD result
RETURN result
```
After this we expect the relationship between e1 and e3 to remain, but it disappears
![image](https://user-images.githubusercontent.com/6514740/69754745-b0260d00-1124-11ea-8b9d-64aae622c7b6.png)

**Expected behavior**
It was expected that when I used `graph.versioner.relationship.delete(e1, e2, 'REL')` only the relationship of type `REL` between the specified nodes was the only one deleted.

**Desktop (please complete the following information):**
 - OS: MacOS Mohave Version 10.14.5 (18F132)
 - Browser Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Additional context**

**Comment by mfalcier** [comment]
Solved with release of version 2.0.3
