### ISSUE TITLE
Current Maintenance Status?

### ISSUE THREAD

**Issue by BHunter2889** [h-omer/neo4j-versioner-core#9]
### What am I experiencing
- Client wants us to document the maintenance status of all open source components we use in building their solution. They want use to version all of our data to justify using Neo4j. Your plugin appears to be the most fully fledged we've found but hasn't seen any commits in the last few months. We would appreciate if some sort of status on maintenance could be posted somewhere (e.g. - Actively Maintained - Stable as of Neo4j v4.0.1 ) perhaps such as the ReadMe. 

### What am I using
Neo4j v4.0.2 
latest release of neo4j-versioner-core (2.0.1?)

**Comment by mfalcier** [comment]
Hi Brandon, will keep you posted on this.

**Comment by aelgn** [comment]
I'm also very interested in the status of this project.
@mfalcier It does seem like this project has gone stale, is that a fair assessment?

**Comment by mfalcier** [comment]
@BHunter2889 @aelgn We are currently working on Neo4j 4.2 support that has been released 7 days ago. Right now we will skip 4.0 due to lack of free time.

**Comment by mfalcier** [comment]
New release with version 4.2 support.
https://github.com/h-omer/neo4j-versioner-core/releases/tag/4.2.4
